-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/OAuthRateLimiter/schema/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/oauth_ratelimit_client_tier (
  oarct_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  oarct_client_id VARCHAR(32) NOT NULL,
  oarct_tier_name VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX oarct_client_id ON /*_*/oauth_ratelimit_client_tier (oarct_client_id);
